// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/labstack/echo/v4"
	"go-api/internal/modules/hello/domain/service"
	"go-api/internal/modules/hello/handler"
	"go-api/internal/modules/hello/usecase"
	"go-api/internal/shared/interface/router"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	echoEcho := echo.New()
	routerRouter := router.NewRouter(echoEcho)
	helloService := service.NewHelloService()
	helloUseCase := usecase.NewHelloUseCase(helloService)
	helloHandler := handler.NewHelloHandler(helloUseCase)
	server := NewServer(echoEcho, routerRouter, helloHandler)
	return server, nil
}

// wire.go:

// Server はアプリケーションサーバーを表します
type Server struct {
	echo         *echo.Echo
	router       *router.Router
	helloHandler *handler.HelloHandler
}

// NewServer は新しいServerを作成します
func NewServer(e *echo.Echo, r *router.Router, h *handler.HelloHandler) *Server {
	return &Server{
		echo:         e,
		router:       r,
		helloHandler: h,
	}
}

// Start はサーバーを起動します
func (s *Server) Start(addr string) error {

	s.router.SetupRoutes(s.helloHandler)

	return s.echo.Start(addr)
}
